#server
server:
  port: 80
  servelt:
    context-path: /
  tomcat:
    max-Threads: 1000
    
    
#spring
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT&characterEncoding=UTF8
    username: root
    password: root
  thymeleaf:
      prefix: classpath:/templates/pages/
      suffix: .html
        

#mybatis
mybatis:
  configuration: 
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/sys/*.xml

#log
logging:
  level:
    com.cy: DEBUG
  
#page
page.config:
  pageSize: 5
 
      











  
